[project]
name = "oasync"
version = "0.1.0"
description = "Synchronize group assignments between an Outline document and Authentik using Outline webhooks."
authors = [{ name = "Mix", email = "32300164+mnixry@users.noreply.github.com" }]
dependencies = [
    "fastapi[standard]>=0.115.2",
    "pydantic-settings>=2.5.2",
    "aiohttp[speedup]>=3.10.10",
    "outline-openapi",
    "authentik-openapi",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "AGPL-3.0-only" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
