# coding: utf-8

# flake8: noqa
"""
    Outline API

    # Introduction  The Outline API is structured in an RPC style. It enables you to programatically interact with all aspects of Outline’s data – in fact, the main application is built on exactly the same API.  The API structure is available as an [openapi specification](https://github.com/outline/openapi) if that’s your jam – it can be used to generate clients for most programming languages.  # Making requests  Outline’s API follows simple RPC style conventions where each API endpoint is a `POST` method on `https://app.getoutline.com/api/:method`. Only HTTPS is supported and all response payloads are JSON.  When making `POST` requests, request parameters are parsed depending on Content-Type header. To make a call using JSON payload, you must pass Content-Type: application/json header, here’s an example using CURL:  ``` curl https://app.getoutline.com/api/documents.info \\ -X 'POST' \\ -H 'authorization: Bearer MY_API_KEY' \\ -H 'content-type: application/json' \\ -H 'accept: application/json' \\ -d '{\"id\": \"outline-api-NTpezNwhUP\"}' ```  Or, with JavaScript:  ```javascript const response = await fetch(\"https://app.getoutline.com/api/documents.info\", {   method: \"POST\",   headers: {     Accept: \"application/json\",     \"Content-Type\": \"application/json\",     Authorization: \"Bearer MY_API_KEY\"   } })  const body = await response.json(); const document = body.data; ```  # Authentication  ## API key  You can create new API keys under **Settings => API & Apps**. Be careful when handling your keys as they give access to all of your documents, you should treat them like passwords and they should never be committed to source control.  To authenticate with API, you should supply the API key as the `Authorization` header (`Authorization: Bearer YOUR_API_KEY`).  ## OAuth 2.0  OAuth 2.0 is a widely used protocol for authorization and authentication. It allows users to grant third-party _or_ internal applications access to their resources without sharing their credentials. To use OAuth 2.0 you need to follow these steps:  1. Register your application under **Settings => Applications** 2. Obtain an access token by exchanging the client credentials for an access token 3. Use the access token to authenticate requests to the API  Some API endpoints allow unauthenticated requests for public resources and they can be called without authentication  # Scopes  Scopes are used to limit the access of an API key or application to specific resources. For example, an application may only need access to read documents, but not write them. Scopes can be global in the case of `read` and `write` scopes, scoped to a namespace, scoped to an API endpoint, or use wildcard scopes like `documents.*`. Some examples of scopes that can be used are:  ## Global  - `read`: Allows all read actions - `write`: Allows all read and write actions  ## Namespaced  - `documents:read`: Allows all document read actions - `collections:write`: Allows all collection write actions  ## Endpoints  - `documents.info`: Allows only one specific API method - `documents.*`: Allows all document API methods - `users.*`: Allows all user API methods  # Errors  All successful API requests will be returned with a 200 or 201 status code and `ok: true` in the response payload. If there’s an error while making the request, the appropriate status code is returned with the error message:  ``` {   \"ok\": false,   \"error\": \"Not Found\" } ```  # Pagination  Most top-level API resources have support for \"list\" API methods. For instance, you can list users, documents, and collections. These list methods share common parameters, taking both `limit` and `offset`.  Responses will echo these parameters in the root `pagination` key, and also include a `nextPath` key which can be used as a handy shortcut to fetch the next page of results. For example:  ``` {   ok: true,   status: 200,   data: […],   pagination: {     limit: 25,     offset: 0,     nextPath: \"/api/documents.list?limit=25&offset=25\"   } } ```  # Rate limits  Like most APIs, Outline has rate limits in place to prevent abuse. Endpoints that mutate data are more restrictive than read-only endpoints. If you exceed the rate limit for a given endpoint, you will receive a `429 Too Many Requests` status code.  The response will include a `Retry-After` header that indicates how many seconds you should wait before making another request.  # Policies  Most API resources have associated \"policies\", these objects describe the current authentications authorized actions related to an individual resource. It should be noted that the policy \"id\" is identical to the resource it is related to, policies themselves do not have unique identifiers.  For most usecases of the API, policies can be safely ignored. Calling unauthorized methods will result in the appropriate response code – these can be used in an interface to adjust which elements are visible. 

    The version of the OpenAPI document: 0.1.0
    Contact: hello@getoutline.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from outline_openapi.models.ability import Ability
from outline_openapi.models.attachment import Attachment
from outline_openapi.models.attachments_create200_response import AttachmentsCreate200Response
from outline_openapi.models.attachments_create200_response_data import AttachmentsCreate200ResponseData
from outline_openapi.models.attachments_create_request import AttachmentsCreateRequest
from outline_openapi.models.attachments_delete200_response import AttachmentsDelete200Response
from outline_openapi.models.attachments_redirect_request import AttachmentsRedirectRequest
from outline_openapi.models.auth import Auth
from outline_openapi.models.auth_config200_response import AuthConfig200Response
from outline_openapi.models.auth_config200_response_data import AuthConfig200ResponseData
from outline_openapi.models.auth_config200_response_data_services_inner import AuthConfig200ResponseDataServicesInner
from outline_openapi.models.auth_info200_response import AuthInfo200Response
from outline_openapi.models.collection import Collection
from outline_openapi.models.collection_group_membership import CollectionGroupMembership
from outline_openapi.models.collection_sort import CollectionSort
from outline_openapi.models.collection_status import CollectionStatus
from outline_openapi.models.collections_add_group200_response import CollectionsAddGroup200Response
from outline_openapi.models.collections_add_group200_response_data import CollectionsAddGroup200ResponseData
from outline_openapi.models.collections_add_group_request import CollectionsAddGroupRequest
from outline_openapi.models.collections_add_user200_response import CollectionsAddUser200Response
from outline_openapi.models.collections_add_user200_response_data import CollectionsAddUser200ResponseData
from outline_openapi.models.collections_add_user_request import CollectionsAddUserRequest
from outline_openapi.models.collections_create_request import CollectionsCreateRequest
from outline_openapi.models.collections_delete_request import CollectionsDeleteRequest
from outline_openapi.models.collections_documents200_response import CollectionsDocuments200Response
from outline_openapi.models.collections_export200_response import CollectionsExport200Response
from outline_openapi.models.collections_export200_response_data import CollectionsExport200ResponseData
from outline_openapi.models.collections_export_all_request import CollectionsExportAllRequest
from outline_openapi.models.collections_export_request import CollectionsExportRequest
from outline_openapi.models.collections_group_memberships200_response import CollectionsGroupMemberships200Response
from outline_openapi.models.collections_group_memberships200_response_data import CollectionsGroupMemberships200ResponseData
from outline_openapi.models.collections_group_memberships_request import CollectionsGroupMembershipsRequest
from outline_openapi.models.collections_info200_response import CollectionsInfo200Response
from outline_openapi.models.collections_info_request import CollectionsInfoRequest
from outline_openapi.models.collections_list200_response import CollectionsList200Response
from outline_openapi.models.collections_list_request import CollectionsListRequest
from outline_openapi.models.collections_memberships200_response import CollectionsMemberships200Response
from outline_openapi.models.collections_memberships_request import CollectionsMembershipsRequest
from outline_openapi.models.collections_remove_group_request import CollectionsRemoveGroupRequest
from outline_openapi.models.collections_remove_user_request import CollectionsRemoveUserRequest
from outline_openapi.models.collections_update_request import CollectionsUpdateRequest
from outline_openapi.models.comment import Comment
from outline_openapi.models.comments_create200_response import CommentsCreate200Response
from outline_openapi.models.comments_create_request import CommentsCreateRequest
from outline_openapi.models.comments_info200_response import CommentsInfo200Response
from outline_openapi.models.comments_info_request import CommentsInfoRequest
from outline_openapi.models.comments_list200_response import CommentsList200Response
from outline_openapi.models.comments_list_request import CommentsListRequest
from outline_openapi.models.comments_update_request import CommentsUpdateRequest
from outline_openapi.models.document import Document
from outline_openapi.models.documents_add_user_request import DocumentsAddUserRequest
from outline_openapi.models.documents_answerquestion200_response import DocumentsAnswerquestion200Response
from outline_openapi.models.documents_answerquestion_request import DocumentsAnswerquestionRequest
from outline_openapi.models.documents_create_request import DocumentsCreateRequest
from outline_openapi.models.documents_delete_request import DocumentsDeleteRequest
from outline_openapi.models.documents_drafts_request import DocumentsDraftsRequest
from outline_openapi.models.documents_export200_response import DocumentsExport200Response
from outline_openapi.models.documents_export_request import DocumentsExportRequest
from outline_openapi.models.documents_info200_response import DocumentsInfo200Response
from outline_openapi.models.documents_info_request import DocumentsInfoRequest
from outline_openapi.models.documents_list200_response import DocumentsList200Response
from outline_openapi.models.documents_list_request import DocumentsListRequest
from outline_openapi.models.documents_memberships_request import DocumentsMembershipsRequest
from outline_openapi.models.documents_move200_response import DocumentsMove200Response
from outline_openapi.models.documents_move200_response_data import DocumentsMove200ResponseData
from outline_openapi.models.documents_move_request import DocumentsMoveRequest
from outline_openapi.models.documents_remove_user_request import DocumentsRemoveUserRequest
from outline_openapi.models.documents_restore_request import DocumentsRestoreRequest
from outline_openapi.models.documents_search200_response import DocumentsSearch200Response
from outline_openapi.models.documents_search200_response_data_inner import DocumentsSearch200ResponseDataInner
from outline_openapi.models.documents_search_request import DocumentsSearchRequest
from outline_openapi.models.documents_unpublish_request import DocumentsUnpublishRequest
from outline_openapi.models.documents_update_request import DocumentsUpdateRequest
from outline_openapi.models.documents_users200_response import DocumentsUsers200Response
from outline_openapi.models.documents_users_request import DocumentsUsersRequest
from outline_openapi.models.documents_viewed_request import DocumentsViewedRequest
from outline_openapi.models.error import Error
from outline_openapi.models.event import Event
from outline_openapi.models.events_list200_response import EventsList200Response
from outline_openapi.models.events_list_request import EventsListRequest
from outline_openapi.models.file_operation import FileOperation
from outline_openapi.models.fileoperations_info200_response import FileoperationsInfo200Response
from outline_openapi.models.fileoperations_info_request import FileoperationsInfoRequest
from outline_openapi.models.fileoperations_list200_response import FileoperationsList200Response
from outline_openapi.models.fileoperations_list_request import FileoperationsListRequest
from outline_openapi.models.group import Group
from outline_openapi.models.group_membership import GroupMembership
from outline_openapi.models.groups_add_user200_response import GroupsAddUser200Response
from outline_openapi.models.groups_add_user200_response_data import GroupsAddUser200ResponseData
from outline_openapi.models.groups_add_user_request import GroupsAddUserRequest
from outline_openapi.models.groups_create_request import GroupsCreateRequest
from outline_openapi.models.groups_info200_response import GroupsInfo200Response
from outline_openapi.models.groups_info_request import GroupsInfoRequest
from outline_openapi.models.groups_list200_response import GroupsList200Response
from outline_openapi.models.groups_list200_response_data import GroupsList200ResponseData
from outline_openapi.models.groups_list_request import GroupsListRequest
from outline_openapi.models.groups_memberships200_response import GroupsMemberships200Response
from outline_openapi.models.groups_memberships200_response_data import GroupsMemberships200ResponseData
from outline_openapi.models.groups_memberships_request import GroupsMembershipsRequest
from outline_openapi.models.groups_remove_user200_response import GroupsRemoveUser200Response
from outline_openapi.models.groups_remove_user200_response_data import GroupsRemoveUser200ResponseData
from outline_openapi.models.groups_update_request import GroupsUpdateRequest
from outline_openapi.models.inline_object import InlineObject
from outline_openapi.models.invite import Invite
from outline_openapi.models.membership import Membership
from outline_openapi.models.navigation_node import NavigationNode
from outline_openapi.models.o_auth_client import OAuthClient
from outline_openapi.models.oauth_clients_create_request import OauthClientsCreateRequest
from outline_openapi.models.oauth_clients_info200_response import OauthClientsInfo200Response
from outline_openapi.models.oauth_clients_info_request import OauthClientsInfoRequest
from outline_openapi.models.oauth_clients_list200_response import OauthClientsList200Response
from outline_openapi.models.oauth_clients_rotate_secret_request import OauthClientsRotateSecretRequest
from outline_openapi.models.oauth_clients_update_request import OauthClientsUpdateRequest
from outline_openapi.models.pagination import Pagination
from outline_openapi.models.permission import Permission
from outline_openapi.models.policy import Policy
from outline_openapi.models.revision import Revision
from outline_openapi.models.revisions_info200_response import RevisionsInfo200Response
from outline_openapi.models.revisions_info_request import RevisionsInfoRequest
from outline_openapi.models.revisions_list200_response import RevisionsList200Response
from outline_openapi.models.revisions_list_request import RevisionsListRequest
from outline_openapi.models.search_result import SearchResult
from outline_openapi.models.share import Share
from outline_openapi.models.shares_create_request import SharesCreateRequest
from outline_openapi.models.shares_info200_response import SharesInfo200Response
from outline_openapi.models.shares_info_request import SharesInfoRequest
from outline_openapi.models.shares_list200_response import SharesList200Response
from outline_openapi.models.shares_list_request import SharesListRequest
from outline_openapi.models.shares_update_request import SharesUpdateRequest
from outline_openapi.models.sorting import Sorting
from outline_openapi.models.star import Star
from outline_openapi.models.stars_create200_response import StarsCreate200Response
from outline_openapi.models.stars_create_request import StarsCreateRequest
from outline_openapi.models.stars_list200_response import StarsList200Response
from outline_openapi.models.stars_list200_response_data import StarsList200ResponseData
from outline_openapi.models.stars_update_request import StarsUpdateRequest
from outline_openapi.models.team import Team
from outline_openapi.models.user import User
from outline_openapi.models.user_role import UserRole
from outline_openapi.models.users_info200_response import UsersInfo200Response
from outline_openapi.models.users_info_request import UsersInfoRequest
from outline_openapi.models.users_invite200_response import UsersInvite200Response
from outline_openapi.models.users_invite200_response_data import UsersInvite200ResponseData
from outline_openapi.models.users_invite_request import UsersInviteRequest
from outline_openapi.models.users_list200_response import UsersList200Response
from outline_openapi.models.users_list_request import UsersListRequest
from outline_openapi.models.users_update_request import UsersUpdateRequest
from outline_openapi.models.users_update_role_request import UsersUpdateRoleRequest
from outline_openapi.models.view import View
from outline_openapi.models.views_create200_response import ViewsCreate200Response
from outline_openapi.models.views_list200_response import ViewsList200Response
from outline_openapi.models.views_list_request import ViewsListRequest
