# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi import util


class AttachmentsDeletePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, success: bool=None):
        """AttachmentsDeletePost200Response - a model defined in OpenAPI

        :param success: The success of this AttachmentsDeletePost200Response.
        """
        self.openapi_types = {
            'success': bool
        }

        self.attribute_map = {
            'success': 'success'
        }

        self._success = success

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AttachmentsDeletePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _attachments_delete_post_200_response of this AttachmentsDeletePost200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def success(self):
        """Gets the success of this AttachmentsDeletePost200Response.


        :return: The success of this AttachmentsDeletePost200Response.
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this AttachmentsDeletePost200Response.


        :param success: The success of this AttachmentsDeletePost200Response.
        :type success: bool
        """

        self._success = success
