# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.team import Team
from outline_openapi.models.user import User
from outline_openapi import util


class Auth(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user: User=None, team: Team=None):
        """Auth - a model defined in OpenAPI

        :param user: The user of this Auth.
        :param team: The team of this Auth.
        """
        self.openapi_types = {
            'user': User,
            'team': Team
        }

        self.attribute_map = {
            'user': 'user',
            'team': 'team'
        }

        self._user = user
        self._team = team

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Auth':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Auth of this Auth.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user(self):
        """Gets the user of this Auth.


        :return: The user of this Auth.
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Auth.


        :param user: The user of this Auth.
        :type user: User
        """

        self._user = user

    @property
    def team(self):
        """Gets the team of this Auth.


        :return: The team of this Auth.
        :rtype: Team
        """
        return self._team

    @team.setter
    def team(self, team):
        """Sets the team of this Auth.


        :param team: The team of this Auth.
        :type team: Team
        """

        self._team = team
