# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.collection_group_membership import CollectionGroupMembership
from outline_openapi.models.group import Group
from outline_openapi import util


class CollectionsGroupMembershipsPost200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, groups: List[Group]=None, collection_group_memberships: List[CollectionGroupMembership]=None):
        """CollectionsGroupMembershipsPost200ResponseData - a model defined in OpenAPI

        :param groups: The groups of this CollectionsGroupMembershipsPost200ResponseData.
        :param collection_group_memberships: The collection_group_memberships of this CollectionsGroupMembershipsPost200ResponseData.
        """
        self.openapi_types = {
            'groups': List[Group],
            'collection_group_memberships': List[CollectionGroupMembership]
        }

        self.attribute_map = {
            'groups': 'groups',
            'collection_group_memberships': 'collectionGroupMemberships'
        }

        self._groups = groups
        self._collection_group_memberships = collection_group_memberships

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CollectionsGroupMembershipsPost200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _collections_group_memberships_post_200_response_data of this CollectionsGroupMembershipsPost200ResponseData.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def groups(self):
        """Gets the groups of this CollectionsGroupMembershipsPost200ResponseData.


        :return: The groups of this CollectionsGroupMembershipsPost200ResponseData.
        :rtype: List[Group]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this CollectionsGroupMembershipsPost200ResponseData.


        :param groups: The groups of this CollectionsGroupMembershipsPost200ResponseData.
        :type groups: List[Group]
        """

        self._groups = groups

    @property
    def collection_group_memberships(self):
        """Gets the collection_group_memberships of this CollectionsGroupMembershipsPost200ResponseData.


        :return: The collection_group_memberships of this CollectionsGroupMembershipsPost200ResponseData.
        :rtype: List[CollectionGroupMembership]
        """
        return self._collection_group_memberships

    @collection_group_memberships.setter
    def collection_group_memberships(self, collection_group_memberships):
        """Sets the collection_group_memberships of this CollectionsGroupMembershipsPost200ResponseData.


        :param collection_group_memberships: The collection_group_memberships of this CollectionsGroupMembershipsPost200ResponseData.
        :type collection_group_memberships: List[CollectionGroupMembership]
        """

        self._collection_group_memberships = collection_group_memberships
