# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.file_operation import FileOperation
from outline_openapi import util


class CollectionsExportPost200ResponseData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, file_operation: FileOperation=None):
        """CollectionsExportPost200ResponseData - a model defined in OpenAPI

        :param file_operation: The file_operation of this CollectionsExportPost200ResponseData.
        """
        self.openapi_types = {
            'file_operation': FileOperation
        }

        self.attribute_map = {
            'file_operation': 'fileOperation'
        }

        self._file_operation = file_operation

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CollectionsExportPost200ResponseData':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _collections_export_post_200_response_data of this CollectionsExportPost200ResponseData.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_operation(self):
        """Gets the file_operation of this CollectionsExportPost200ResponseData.


        :return: The file_operation of this CollectionsExportPost200ResponseData.
        :rtype: FileOperation
        """
        return self._file_operation

    @file_operation.setter
    def file_operation(self, file_operation):
        """Sets the file_operation of this CollectionsExportPost200ResponseData.


        :param file_operation: The file_operation of this CollectionsExportPost200ResponseData.
        :type file_operation: FileOperation
        """

        self._file_operation = file_operation
