# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.permission import Permission
from outline_openapi import util


class CollectionsCreatePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, description: str=None, permission: Permission=None, color: str=None, private: bool=None):
        """CollectionsCreatePostRequest - a model defined in OpenAPI

        :param name: The name of this CollectionsCreatePostRequest.
        :param description: The description of this CollectionsCreatePostRequest.
        :param permission: The permission of this CollectionsCreatePostRequest.
        :param color: The color of this CollectionsCreatePostRequest.
        :param private: The private of this CollectionsCreatePostRequest.
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'permission': Permission,
            'color': str,
            'private': bool
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'permission': 'permission',
            'color': 'color',
            'private': 'private'
        }

        self._name = name
        self._description = description
        self._permission = permission
        self._color = color
        self._private = private

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CollectionsCreatePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _collections_create_post_request of this CollectionsCreatePostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this CollectionsCreatePostRequest.


        :return: The name of this CollectionsCreatePostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CollectionsCreatePostRequest.


        :param name: The name of this CollectionsCreatePostRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def description(self):
        """Gets the description of this CollectionsCreatePostRequest.


        :return: The description of this CollectionsCreatePostRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this CollectionsCreatePostRequest.


        :param description: The description of this CollectionsCreatePostRequest.
        :type description: str
        """

        self._description = description

    @property
    def permission(self):
        """Gets the permission of this CollectionsCreatePostRequest.


        :return: The permission of this CollectionsCreatePostRequest.
        :rtype: Permission
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this CollectionsCreatePostRequest.


        :param permission: The permission of this CollectionsCreatePostRequest.
        :type permission: Permission
        """

        self._permission = permission

    @property
    def color(self):
        """Gets the color of this CollectionsCreatePostRequest.


        :return: The color of this CollectionsCreatePostRequest.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this CollectionsCreatePostRequest.


        :param color: The color of this CollectionsCreatePostRequest.
        :type color: str
        """

        self._color = color

    @property
    def private(self):
        """Gets the private of this CollectionsCreatePostRequest.


        :return: The private of this CollectionsCreatePostRequest.
        :rtype: bool
        """
        return self._private

    @private.setter
    def private(self, private):
        """Sets the private of this CollectionsCreatePostRequest.


        :param private: The private of this CollectionsCreatePostRequest.
        :type private: bool
        """

        self._private = private
