# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.permission import Permission
from outline_openapi import util


class CollectionsAddGroupPostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, group_id: str=None, permission: Permission=None):
        """CollectionsAddGroupPostRequest - a model defined in OpenAPI

        :param id: The id of this CollectionsAddGroupPostRequest.
        :param group_id: The group_id of this CollectionsAddGroupPostRequest.
        :param permission: The permission of this CollectionsAddGroupPostRequest.
        """
        self.openapi_types = {
            'id': str,
            'group_id': str,
            'permission': Permission
        }

        self.attribute_map = {
            'id': 'id',
            'group_id': 'groupId',
            'permission': 'permission'
        }

        self._id = id
        self._group_id = group_id
        self._permission = permission

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CollectionsAddGroupPostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _collections_add_group_post_request of this CollectionsAddGroupPostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this CollectionsAddGroupPostRequest.


        :return: The id of this CollectionsAddGroupPostRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CollectionsAddGroupPostRequest.


        :param id: The id of this CollectionsAddGroupPostRequest.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def group_id(self):
        """Gets the group_id of this CollectionsAddGroupPostRequest.


        :return: The group_id of this CollectionsAddGroupPostRequest.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this CollectionsAddGroupPostRequest.


        :param group_id: The group_id of this CollectionsAddGroupPostRequest.
        :type group_id: str
        """
        if group_id is None:
            raise ValueError("Invalid value for `group_id`, must not be `None`")

        self._group_id = group_id

    @property
    def permission(self):
        """Gets the permission of this CollectionsAddGroupPostRequest.


        :return: The permission of this CollectionsAddGroupPostRequest.
        :rtype: Permission
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this CollectionsAddGroupPostRequest.


        :param permission: The permission of this CollectionsAddGroupPostRequest.
        :type permission: Permission
        """

        self._permission = permission
