# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.comment import Comment
from outline_openapi import util


class CommentsCreatePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: Comment=None):
        """CommentsCreatePost200Response - a model defined in OpenAPI

        :param data: The data of this CommentsCreatePost200Response.
        """
        self.openapi_types = {
            'data': Comment
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CommentsCreatePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _comments_create_post_200_response of this CommentsCreatePost200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CommentsCreatePost200Response.


        :return: The data of this CommentsCreatePost200Response.
        :rtype: Comment
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CommentsCreatePost200Response.


        :param data: The data of this CommentsCreatePost200Response.
        :type data: Comment
        """

        self._data = data
