# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi import util


class DocumentsDeletePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, permanent: bool=None):
        """DocumentsDeletePostRequest - a model defined in OpenAPI

        :param id: The id of this DocumentsDeletePostRequest.
        :param permanent: The permanent of this DocumentsDeletePostRequest.
        """
        self.openapi_types = {
            'id': str,
            'permanent': bool
        }

        self.attribute_map = {
            'id': 'id',
            'permanent': 'permanent'
        }

        self._id = id
        self._permanent = permanent

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DocumentsDeletePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _documents_delete_post_request of this DocumentsDeletePostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this DocumentsDeletePostRequest.

        Unique identifier for the document. Either the UUID or the urlId is acceptable.

        :return: The id of this DocumentsDeletePostRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this DocumentsDeletePostRequest.

        Unique identifier for the document. Either the UUID or the urlId is acceptable.

        :param id: The id of this DocumentsDeletePostRequest.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def permanent(self):
        """Gets the permanent of this DocumentsDeletePostRequest.

        If set to true the document will be destroyed with no way to recover rather than moved to the trash.

        :return: The permanent of this DocumentsDeletePostRequest.
        :rtype: bool
        """
        return self._permanent

    @permanent.setter
    def permanent(self, permanent):
        """Sets the permanent of this DocumentsDeletePostRequest.

        If set to true the document will be destroyed with no way to recover rather than moved to the trash.

        :param permanent: The permanent of this DocumentsDeletePostRequest.
        :type permanent: bool
        """

        self._permanent = permanent
