# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.groups_list_post200_response_data import GroupsListPost200ResponseData
from outline_openapi.models.pagination import Pagination
from outline_openapi import util


class GroupsListPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: GroupsListPost200ResponseData=None, pagination: Pagination=None):
        """GroupsListPost200Response - a model defined in OpenAPI

        :param data: The data of this GroupsListPost200Response.
        :param pagination: The pagination of this GroupsListPost200Response.
        """
        self.openapi_types = {
            'data': GroupsListPost200ResponseData,
            'pagination': Pagination
        }

        self.attribute_map = {
            'data': 'data',
            'pagination': 'pagination'
        }

        self._data = data
        self._pagination = pagination

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GroupsListPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _groups_list_post_200_response of this GroupsListPost200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GroupsListPost200Response.


        :return: The data of this GroupsListPost200Response.
        :rtype: GroupsListPost200ResponseData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GroupsListPost200Response.


        :param data: The data of this GroupsListPost200Response.
        :type data: GroupsListPost200ResponseData
        """

        self._data = data

    @property
    def pagination(self):
        """Gets the pagination of this GroupsListPost200Response.


        :return: The pagination of this GroupsListPost200Response.
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this GroupsListPost200Response.


        :param pagination: The pagination of this GroupsListPost200Response.
        :type pagination: Pagination
        """

        self._pagination = pagination
