# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.user_role import UserRole
from outline_openapi import util


class Invite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, email: str=None, role: UserRole=None):
        """Invite - a model defined in OpenAPI

        :param name: The name of this Invite.
        :param email: The email of this Invite.
        :param role: The role of this Invite.
        """
        self.openapi_types = {
            'name': str,
            'email': str,
            'role': UserRole
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'role': 'role'
        }

        self._name = name
        self._email = email
        self._role = role

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Invite':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Invite of this Invite.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Invite.

        The full name of the user being invited

        :return: The name of this Invite.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Invite.

        The full name of the user being invited

        :param name: The name of this Invite.
        :type name: str
        """

        self._name = name

    @property
    def email(self):
        """Gets the email of this Invite.

        The email address to invite

        :return: The email of this Invite.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Invite.

        The email address to invite

        :param email: The email of this Invite.
        :type email: str
        """

        self._email = email

    @property
    def role(self):
        """Gets the role of this Invite.


        :return: The role of this Invite.
        :rtype: UserRole
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this Invite.


        :param role: The role of this Invite.
        :type role: UserRole
        """

        self._role = role
