# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.user_role import UserRole
from outline_openapi import util


class UsersUpdateRolePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, role: UserRole=None):
        """UsersUpdateRolePostRequest - a model defined in OpenAPI

        :param id: The id of this UsersUpdateRolePostRequest.
        :param role: The role of this UsersUpdateRolePostRequest.
        """
        self.openapi_types = {
            'id': str,
            'role': UserRole
        }

        self.attribute_map = {
            'id': 'id',
            'role': 'role'
        }

        self._id = id
        self._role = role

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UsersUpdateRolePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _users_update_role_post_request of this UsersUpdateRolePostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this UsersUpdateRolePostRequest.

        Unique identifier for the user.

        :return: The id of this UsersUpdateRolePostRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UsersUpdateRolePostRequest.

        Unique identifier for the user.

        :param id: The id of this UsersUpdateRolePostRequest.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def role(self):
        """Gets the role of this UsersUpdateRolePostRequest.


        :return: The role of this UsersUpdateRolePostRequest.
        :rtype: UserRole
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this UsersUpdateRolePostRequest.


        :param role: The role of this UsersUpdateRolePostRequest.
        :type role: UserRole
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")

        self._role = role
