# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.user import User
from outline_openapi import util


class UsersInfoPost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: User=None):
        """UsersInfoPost200Response - a model defined in OpenAPI

        :param data: The data of this UsersInfoPost200Response.
        """
        self.openapi_types = {
            'data': User
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UsersInfoPost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _users_info_post_200_response of this UsersInfoPost200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this UsersInfoPost200Response.


        :return: The data of this UsersInfoPost200Response.
        :rtype: User
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this UsersInfoPost200Response.


        :param data: The data of this UsersInfoPost200Response.
        :type data: User
        """

        self._data = data
