# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from outline_openapi.models.base_model import Model
from outline_openapi.models.users_invite_post200_response_data import UsersInvitePost200ResponseData
from outline_openapi import util


class UsersInvitePost200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: UsersInvitePost200ResponseData=None):
        """UsersInvitePost200Response - a model defined in OpenAPI

        :param data: The data of this UsersInvitePost200Response.
        """
        self.openapi_types = {
            'data': UsersInvitePost200ResponseData
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UsersInvitePost200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The _users_invite_post_200_response of this UsersInvitePost200Response.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this UsersInvitePost200Response.


        :return: The data of this UsersInvitePost200Response.
        :rtype: UsersInvitePost200ResponseData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this UsersInvitePost200Response.


        :param data: The data of this UsersInvitePost200Response.
        :type data: UsersInvitePost200ResponseData
        """

        self._data = data
