# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class BackendsEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AUTHENTIK_PERIOD_CORE_PERIOD_AUTH_PERIOD_INBUILT_BACKEND = 'authentik.core.auth.InbuiltBackend'
    AUTHENTIK_PERIOD_CORE_PERIOD_AUTH_PERIOD_TOKEN_BACKEND = 'authentik.core.auth.TokenBackend'
    AUTHENTIK_PERIOD_SOURCES_PERIOD_LDAP_PERIOD_AUTH_PERIOD_LDAP_BACKEND = 'authentik.sources.ldap.auth.LDAPBackend'

    def __init__(self):
        """BackendsEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BackendsEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BackendsEnum of this BackendsEnum.
        """
        return util.deserialize_model(dikt, cls)
