# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class CaptchaChallengeResponseRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, component: str='ak-stage-captcha', token: str=None):
        """CaptchaChallengeResponseRequest - a model defined in OpenAPI

        :param component: The component of this CaptchaChallengeResponseRequest.
        :param token: The token of this CaptchaChallengeResponseRequest.
        """
        self.openapi_types = {
            'component': str,
            'token': str
        }

        self.attribute_map = {
            'component': 'component',
            'token': 'token'
        }

        self._component = component
        self._token = token

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CaptchaChallengeResponseRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CaptchaChallengeResponseRequest of this CaptchaChallengeResponseRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def component(self):
        """Gets the component of this CaptchaChallengeResponseRequest.


        :return: The component of this CaptchaChallengeResponseRequest.
        :rtype: str
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this CaptchaChallengeResponseRequest.


        :param component: The component of this CaptchaChallengeResponseRequest.
        :type component: str
        """
        if component is not None and len(component) < 1:
            raise ValueError("Invalid value for `component`, length must be greater than or equal to `1`")

        self._component = component

    @property
    def token(self):
        """Gets the token of this CaptchaChallengeResponseRequest.


        :return: The token of this CaptchaChallengeResponseRequest.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this CaptchaChallengeResponseRequest.


        :param token: The token of this CaptchaChallengeResponseRequest.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")
        if token is not None and len(token) < 1:
            raise ValueError("Invalid value for `token`, length must be greater than or equal to `1`")

        self._token = token
