# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.event_actions import EventActions
from authentik_openapi import util


class Event(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pk: str=None, user: object=None, action: EventActions=None, app: str=None, context: object=None, client_ip: str=None, created: datetime=None, expires: datetime=None, brand: object=None):
        """Event - a model defined in OpenAPI

        :param pk: The pk of this Event.
        :param user: The user of this Event.
        :param action: The action of this Event.
        :param app: The app of this Event.
        :param context: The context of this Event.
        :param client_ip: The client_ip of this Event.
        :param created: The created of this Event.
        :param expires: The expires of this Event.
        :param brand: The brand of this Event.
        """
        self.openapi_types = {
            'pk': str,
            'user': object,
            'action': EventActions,
            'app': str,
            'context': object,
            'client_ip': str,
            'created': datetime,
            'expires': datetime,
            'brand': object
        }

        self.attribute_map = {
            'pk': 'pk',
            'user': 'user',
            'action': 'action',
            'app': 'app',
            'context': 'context',
            'client_ip': 'client_ip',
            'created': 'created',
            'expires': 'expires',
            'brand': 'brand'
        }

        self._pk = pk
        self._user = user
        self._action = action
        self._app = app
        self._context = context
        self._client_ip = client_ip
        self._created = created
        self._expires = expires
        self._brand = brand

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Event':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Event of this Event.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pk(self):
        """Gets the pk of this Event.


        :return: The pk of this Event.
        :rtype: str
        """
        return self._pk

    @pk.setter
    def pk(self, pk):
        """Sets the pk of this Event.


        :param pk: The pk of this Event.
        :type pk: str
        """
        if pk is None:
            raise ValueError("Invalid value for `pk`, must not be `None`")

        self._pk = pk

    @property
    def user(self):
        """Gets the user of this Event.


        :return: The user of this Event.
        :rtype: object
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Event.


        :param user: The user of this Event.
        :type user: object
        """

        self._user = user

    @property
    def action(self):
        """Gets the action of this Event.


        :return: The action of this Event.
        :rtype: EventActions
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this Event.


        :param action: The action of this Event.
        :type action: EventActions
        """
        if action is None:
            raise ValueError("Invalid value for `action`, must not be `None`")

        self._action = action

    @property
    def app(self):
        """Gets the app of this Event.


        :return: The app of this Event.
        :rtype: str
        """
        return self._app

    @app.setter
    def app(self, app):
        """Sets the app of this Event.


        :param app: The app of this Event.
        :type app: str
        """
        if app is None:
            raise ValueError("Invalid value for `app`, must not be `None`")

        self._app = app

    @property
    def context(self):
        """Gets the context of this Event.


        :return: The context of this Event.
        :rtype: object
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this Event.


        :param context: The context of this Event.
        :type context: object
        """

        self._context = context

    @property
    def client_ip(self):
        """Gets the client_ip of this Event.


        :return: The client_ip of this Event.
        :rtype: str
        """
        return self._client_ip

    @client_ip.setter
    def client_ip(self, client_ip):
        """Sets the client_ip of this Event.


        :param client_ip: The client_ip of this Event.
        :type client_ip: str
        """

        self._client_ip = client_ip

    @property
    def created(self):
        """Gets the created of this Event.


        :return: The created of this Event.
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this Event.


        :param created: The created of this Event.
        :type created: datetime
        """
        if created is None:
            raise ValueError("Invalid value for `created`, must not be `None`")

        self._created = created

    @property
    def expires(self):
        """Gets the expires of this Event.


        :return: The expires of this Event.
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this Event.


        :param expires: The expires of this Event.
        :type expires: datetime
        """

        self._expires = expires

    @property
    def brand(self):
        """Gets the brand of this Event.


        :return: The brand of this Event.
        :rtype: object
        """
        return self._brand

    @brand.setter
    def brand(self, brand):
        """Sets the brand of this Event.


        :param brand: The brand of this Event.
        :type brand: object
        """

        self._brand = brand
