# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class FlowLayoutEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    STACKED = 'stacked'
    CONTENT_LEFT = 'content_left'
    CONTENT_RIGHT = 'content_right'
    SIDEBAR_LEFT = 'sidebar_left'
    SIDEBAR_RIGHT = 'sidebar_right'

    def __init__(self):
        """FlowLayoutEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'FlowLayoutEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The FlowLayoutEnum of this FlowLayoutEnum.
        """
        return util.deserialize_model(dikt, cls)
