# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class GenericError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, detail: str=None, code: str=None):
        """GenericError - a model defined in OpenAPI

        :param detail: The detail of this GenericError.
        :param code: The code of this GenericError.
        """
        self.openapi_types = {
            'detail': str,
            'code': str
        }

        self.attribute_map = {
            'detail': 'detail',
            'code': 'code'
        }

        self._detail = detail
        self._code = code

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GenericError':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GenericError of this GenericError.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def detail(self):
        """Gets the detail of this GenericError.


        :return: The detail of this GenericError.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this GenericError.


        :param detail: The detail of this GenericError.
        :type detail: str
        """
        if detail is None:
            raise ValueError("Invalid value for `detail`, must not be `None`")

        self._detail = detail

    @property
    def code(self):
        """Gets the code of this GenericError.


        :return: The code of this GenericError.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GenericError.


        :param code: The code of this GenericError.
        :type code: str
        """

        self._code = code
