# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
import re
from authentik_openapi import util


class GroupMemberRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, name: str=None, is_active: bool=None, last_login: datetime=None, email: str=None, attributes: Dict[str, object]=None):
        """GroupMemberRequest - a model defined in OpenAPI

        :param username: The username of this GroupMemberRequest.
        :param name: The name of this GroupMemberRequest.
        :param is_active: The is_active of this GroupMemberRequest.
        :param last_login: The last_login of this GroupMemberRequest.
        :param email: The email of this GroupMemberRequest.
        :param attributes: The attributes of this GroupMemberRequest.
        """
        self.openapi_types = {
            'username': str,
            'name': str,
            'is_active': bool,
            'last_login': datetime,
            'email': str,
            'attributes': Dict[str, object]
        }

        self.attribute_map = {
            'username': 'username',
            'name': 'name',
            'is_active': 'is_active',
            'last_login': 'last_login',
            'email': 'email',
            'attributes': 'attributes'
        }

        self._username = username
        self._name = name
        self._is_active = is_active
        self._last_login = last_login
        self._email = email
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GroupMemberRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GroupMemberRequest of this GroupMemberRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this GroupMemberRequest.

        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.

        :return: The username of this GroupMemberRequest.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this GroupMemberRequest.

        Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.

        :param username: The username of this GroupMemberRequest.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")
        if username is not None and len(username) > 150:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `150`")
        if username is not None and len(username) < 1:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `1`")
        if username is not None and not re.search(r'^[\w.@+-]+$', username):
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[\w.@+-]+$/`")

        self._username = username

    @property
    def name(self):
        """Gets the name of this GroupMemberRequest.

        User's display name.

        :return: The name of this GroupMemberRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GroupMemberRequest.

        User's display name.

        :param name: The name of this GroupMemberRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def is_active(self):
        """Gets the is_active of this GroupMemberRequest.

        Designates whether this user should be treated as active. Unselect this instead of deleting accounts.

        :return: The is_active of this GroupMemberRequest.
        :rtype: bool
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this GroupMemberRequest.

        Designates whether this user should be treated as active. Unselect this instead of deleting accounts.

        :param is_active: The is_active of this GroupMemberRequest.
        :type is_active: bool
        """

        self._is_active = is_active

    @property
    def last_login(self):
        """Gets the last_login of this GroupMemberRequest.


        :return: The last_login of this GroupMemberRequest.
        :rtype: datetime
        """
        return self._last_login

    @last_login.setter
    def last_login(self, last_login):
        """Sets the last_login of this GroupMemberRequest.


        :param last_login: The last_login of this GroupMemberRequest.
        :type last_login: datetime
        """

        self._last_login = last_login

    @property
    def email(self):
        """Gets the email of this GroupMemberRequest.


        :return: The email of this GroupMemberRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this GroupMemberRequest.


        :param email: The email of this GroupMemberRequest.
        :type email: str
        """
        if email is not None and len(email) > 254:
            raise ValueError("Invalid value for `email`, length must be less than or equal to `254`")

        self._email = email

    @property
    def attributes(self):
        """Gets the attributes of this GroupMemberRequest.


        :return: The attributes of this GroupMemberRequest.
        :rtype: Dict[str, object]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this GroupMemberRequest.


        :param attributes: The attributes of this GroupMemberRequest.
        :type attributes: Dict[str, object]
        """

        self._attributes = attributes
