# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.flow import Flow
from authentik_openapi.models.group_member import GroupMember
import re
from authentik_openapi import util


class Invitation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pk: str=None, name: str=None, expires: datetime=None, fixed_data: Dict[str, object]=None, created_by: GroupMember=None, single_use: bool=None, flow: str=None, flow_obj: Flow=None):
        """Invitation - a model defined in OpenAPI

        :param pk: The pk of this Invitation.
        :param name: The name of this Invitation.
        :param expires: The expires of this Invitation.
        :param fixed_data: The fixed_data of this Invitation.
        :param created_by: The created_by of this Invitation.
        :param single_use: The single_use of this Invitation.
        :param flow: The flow of this Invitation.
        :param flow_obj: The flow_obj of this Invitation.
        """
        self.openapi_types = {
            'pk': str,
            'name': str,
            'expires': datetime,
            'fixed_data': Dict[str, object],
            'created_by': GroupMember,
            'single_use': bool,
            'flow': str,
            'flow_obj': Flow
        }

        self.attribute_map = {
            'pk': 'pk',
            'name': 'name',
            'expires': 'expires',
            'fixed_data': 'fixed_data',
            'created_by': 'created_by',
            'single_use': 'single_use',
            'flow': 'flow',
            'flow_obj': 'flow_obj'
        }

        self._pk = pk
        self._name = name
        self._expires = expires
        self._fixed_data = fixed_data
        self._created_by = created_by
        self._single_use = single_use
        self._flow = flow
        self._flow_obj = flow_obj

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Invitation':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The Invitation of this Invitation.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pk(self):
        """Gets the pk of this Invitation.


        :return: The pk of this Invitation.
        :rtype: str
        """
        return self._pk

    @pk.setter
    def pk(self, pk):
        """Sets the pk of this Invitation.


        :param pk: The pk of this Invitation.
        :type pk: str
        """
        if pk is None:
            raise ValueError("Invalid value for `pk`, must not be `None`")

        self._pk = pk

    @property
    def name(self):
        """Gets the name of this Invitation.


        :return: The name of this Invitation.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Invitation.


        :param name: The name of this Invitation.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 50:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `50`")
        if name is not None and not re.search(r'^[-a-zA-Z0-9_]+$', name):
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[-a-zA-Z0-9_]+$/`")

        self._name = name

    @property
    def expires(self):
        """Gets the expires of this Invitation.


        :return: The expires of this Invitation.
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this Invitation.


        :param expires: The expires of this Invitation.
        :type expires: datetime
        """

        self._expires = expires

    @property
    def fixed_data(self):
        """Gets the fixed_data of this Invitation.


        :return: The fixed_data of this Invitation.
        :rtype: Dict[str, object]
        """
        return self._fixed_data

    @fixed_data.setter
    def fixed_data(self, fixed_data):
        """Sets the fixed_data of this Invitation.


        :param fixed_data: The fixed_data of this Invitation.
        :type fixed_data: Dict[str, object]
        """

        self._fixed_data = fixed_data

    @property
    def created_by(self):
        """Gets the created_by of this Invitation.


        :return: The created_by of this Invitation.
        :rtype: GroupMember
        """
        return self._created_by

    @created_by.setter
    def created_by(self, created_by):
        """Sets the created_by of this Invitation.


        :param created_by: The created_by of this Invitation.
        :type created_by: GroupMember
        """
        if created_by is None:
            raise ValueError("Invalid value for `created_by`, must not be `None`")

        self._created_by = created_by

    @property
    def single_use(self):
        """Gets the single_use of this Invitation.

        When enabled, the invitation will be deleted after usage.

        :return: The single_use of this Invitation.
        :rtype: bool
        """
        return self._single_use

    @single_use.setter
    def single_use(self, single_use):
        """Sets the single_use of this Invitation.

        When enabled, the invitation will be deleted after usage.

        :param single_use: The single_use of this Invitation.
        :type single_use: bool
        """

        self._single_use = single_use

    @property
    def flow(self):
        """Gets the flow of this Invitation.

        When set, only the configured flow can use this invitation.

        :return: The flow of this Invitation.
        :rtype: str
        """
        return self._flow

    @flow.setter
    def flow(self, flow):
        """Sets the flow of this Invitation.

        When set, only the configured flow can use this invitation.

        :param flow: The flow of this Invitation.
        :type flow: str
        """

        self._flow = flow

    @property
    def flow_obj(self):
        """Gets the flow_obj of this Invitation.


        :return: The flow_obj of this Invitation.
        :rtype: Flow
        """
        return self._flow_obj

    @flow_obj.setter
    def flow_obj(self, flow_obj):
        """Sets the flow_obj of this Invitation.


        :param flow_obj: The flow_obj of this Invitation.
        :type flow_obj: Flow
        """
        if flow_obj is None:
            raise ValueError("Invalid value for `flow_obj`, must not be `None`")

        self._flow_obj = flow_obj
