# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class NotConfiguredActionEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SKIP = 'skip'
    DENY = 'deny'
    CONFIGURE = 'configure'

    def __init__(self):
        """NotConfiguredActionEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NotConfiguredActionEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NotConfiguredActionEnum of this NotConfiguredActionEnum.
        """
        return util.deserialize_model(dikt, cls)
