# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class OutpostDefaultConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config: Dict[str, object]=None):
        """OutpostDefaultConfig - a model defined in OpenAPI

        :param config: The config of this OutpostDefaultConfig.
        """
        self.openapi_types = {
            'config': Dict[str, object]
        }

        self.attribute_map = {
            'config': 'config'
        }

        self._config = config

    @classmethod
    def from_dict(cls, dikt: dict) -> 'OutpostDefaultConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The OutpostDefaultConfig of this OutpostDefaultConfig.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self):
        """Gets the config of this OutpostDefaultConfig.


        :return: The config of this OutpostDefaultConfig.
        :rtype: Dict[str, object]
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this OutpostDefaultConfig.


        :param config: The config of this OutpostDefaultConfig.
        :type config: Dict[str, object]
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")

        self._config = config
