# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class PatchedSCIMSourceUserRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, user: int=None, source: str=None, attributes: object=None):
        """PatchedSCIMSourceUserRequest - a model defined in OpenAPI

        :param id: The id of this PatchedSCIMSourceUserRequest.
        :param user: The user of this PatchedSCIMSourceUserRequest.
        :param source: The source of this PatchedSCIMSourceUserRequest.
        :param attributes: The attributes of this PatchedSCIMSourceUserRequest.
        """
        self.openapi_types = {
            'id': str,
            'user': int,
            'source': str,
            'attributes': object
        }

        self.attribute_map = {
            'id': 'id',
            'user': 'user',
            'source': 'source',
            'attributes': 'attributes'
        }

        self._id = id
        self._user = user
        self._source = source
        self._attributes = attributes

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedSCIMSourceUserRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedSCIMSourceUserRequest of this PatchedSCIMSourceUserRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this PatchedSCIMSourceUserRequest.


        :return: The id of this PatchedSCIMSourceUserRequest.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PatchedSCIMSourceUserRequest.


        :param id: The id of this PatchedSCIMSourceUserRequest.
        :type id: str
        """
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")

        self._id = id

    @property
    def user(self):
        """Gets the user of this PatchedSCIMSourceUserRequest.


        :return: The user of this PatchedSCIMSourceUserRequest.
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this PatchedSCIMSourceUserRequest.


        :param user: The user of this PatchedSCIMSourceUserRequest.
        :type user: int
        """

        self._user = user

    @property
    def source(self):
        """Gets the source of this PatchedSCIMSourceUserRequest.


        :return: The source of this PatchedSCIMSourceUserRequest.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this PatchedSCIMSourceUserRequest.


        :param source: The source of this PatchedSCIMSourceUserRequest.
        :type source: str
        """

        self._source = source

    @property
    def attributes(self):
        """Gets the attributes of this PatchedSCIMSourceUserRequest.


        :return: The attributes of this PatchedSCIMSourceUserRequest.
        :rtype: object
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this PatchedSCIMSourceUserRequest.


        :param attributes: The attributes of this PatchedSCIMSourceUserRequest.
        :type attributes: object
        """

        self._attributes = attributes
