# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class PatchedExtraUserObjectPermissionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, object_pk: str=None):
        """PatchedExtraUserObjectPermissionRequest - a model defined in OpenAPI

        :param object_pk: The object_pk of this PatchedExtraUserObjectPermissionRequest.
        """
        self.openapi_types = {
            'object_pk': str
        }

        self.attribute_map = {
            'object_pk': 'object_pk'
        }

        self._object_pk = object_pk

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedExtraUserObjectPermissionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedExtraUserObjectPermissionRequest of this PatchedExtraUserObjectPermissionRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def object_pk(self):
        """Gets the object_pk of this PatchedExtraUserObjectPermissionRequest.


        :return: The object_pk of this PatchedExtraUserObjectPermissionRequest.
        :rtype: str
        """
        return self._object_pk

    @object_pk.setter
    def object_pk(self, object_pk):
        """Sets the object_pk of this PatchedExtraUserObjectPermissionRequest.


        :param object_pk: The object_pk of this PatchedExtraUserObjectPermissionRequest.
        :type object_pk: str
        """
        if object_pk is not None and len(object_pk) < 1:
            raise ValueError("Invalid value for `object_pk`, length must be greater than or equal to `1`")

        self._object_pk = object_pk
