# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.outpost_type_enum import OutpostTypeEnum
from authentik_openapi import util


class PatchedOutpostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, type: OutpostTypeEnum=None, providers: List[int]=None, service_connection: str=None, config: Dict[str, object]=None, managed: str=None):
        """PatchedOutpostRequest - a model defined in OpenAPI

        :param name: The name of this PatchedOutpostRequest.
        :param type: The type of this PatchedOutpostRequest.
        :param providers: The providers of this PatchedOutpostRequest.
        :param service_connection: The service_connection of this PatchedOutpostRequest.
        :param config: The config of this PatchedOutpostRequest.
        :param managed: The managed of this PatchedOutpostRequest.
        """
        self.openapi_types = {
            'name': str,
            'type': OutpostTypeEnum,
            'providers': List[int],
            'service_connection': str,
            'config': Dict[str, object],
            'managed': str
        }

        self.attribute_map = {
            'name': 'name',
            'type': 'type',
            'providers': 'providers',
            'service_connection': 'service_connection',
            'config': 'config',
            'managed': 'managed'
        }

        self._name = name
        self._type = type
        self._providers = providers
        self._service_connection = service_connection
        self._config = config
        self._managed = managed

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedOutpostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedOutpostRequest of this PatchedOutpostRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this PatchedOutpostRequest.


        :return: The name of this PatchedOutpostRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PatchedOutpostRequest.


        :param name: The name of this PatchedOutpostRequest.
        :type name: str
        """
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def type(self):
        """Gets the type of this PatchedOutpostRequest.


        :return: The type of this PatchedOutpostRequest.
        :rtype: OutpostTypeEnum
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PatchedOutpostRequest.


        :param type: The type of this PatchedOutpostRequest.
        :type type: OutpostTypeEnum
        """

        self._type = type

    @property
    def providers(self):
        """Gets the providers of this PatchedOutpostRequest.


        :return: The providers of this PatchedOutpostRequest.
        :rtype: List[int]
        """
        return self._providers

    @providers.setter
    def providers(self, providers):
        """Sets the providers of this PatchedOutpostRequest.


        :param providers: The providers of this PatchedOutpostRequest.
        :type providers: List[int]
        """

        self._providers = providers

    @property
    def service_connection(self):
        """Gets the service_connection of this PatchedOutpostRequest.

        Select Service-Connection authentik should use to manage this outpost. Leave empty if authentik should not handle the deployment.

        :return: The service_connection of this PatchedOutpostRequest.
        :rtype: str
        """
        return self._service_connection

    @service_connection.setter
    def service_connection(self, service_connection):
        """Sets the service_connection of this PatchedOutpostRequest.

        Select Service-Connection authentik should use to manage this outpost. Leave empty if authentik should not handle the deployment.

        :param service_connection: The service_connection of this PatchedOutpostRequest.
        :type service_connection: str
        """

        self._service_connection = service_connection

    @property
    def config(self):
        """Gets the config of this PatchedOutpostRequest.


        :return: The config of this PatchedOutpostRequest.
        :rtype: Dict[str, object]
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this PatchedOutpostRequest.


        :param config: The config of this PatchedOutpostRequest.
        :type config: Dict[str, object]
        """

        self._config = config

    @property
    def managed(self):
        """Gets the managed of this PatchedOutpostRequest.

        Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.

        :return: The managed of this PatchedOutpostRequest.
        :rtype: str
        """
        return self._managed

    @managed.setter
    def managed(self, managed):
        """Sets the managed of this PatchedOutpostRequest.

        Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update.

        :param managed: The managed of this PatchedOutpostRequest.
        :type managed: str
        """
        if managed is not None and len(managed) < 1:
            raise ValueError("Invalid value for `managed`, length must be greater than or equal to `1`")

        self._managed = managed
