# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.prompt_type_enum import PromptTypeEnum
from authentik_openapi.models.stage_request import StageRequest
from authentik_openapi import util


class PatchedPromptRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, field_key: str=None, label: str=None, type: PromptTypeEnum=None, required: bool=None, placeholder: str=None, initial_value: str=None, order: int=None, promptstage_set: List[StageRequest]=None, sub_text: str=None, placeholder_expression: bool=None, initial_value_expression: bool=None):
        """PatchedPromptRequest - a model defined in OpenAPI

        :param name: The name of this PatchedPromptRequest.
        :param field_key: The field_key of this PatchedPromptRequest.
        :param label: The label of this PatchedPromptRequest.
        :param type: The type of this PatchedPromptRequest.
        :param required: The required of this PatchedPromptRequest.
        :param placeholder: The placeholder of this PatchedPromptRequest.
        :param initial_value: The initial_value of this PatchedPromptRequest.
        :param order: The order of this PatchedPromptRequest.
        :param promptstage_set: The promptstage_set of this PatchedPromptRequest.
        :param sub_text: The sub_text of this PatchedPromptRequest.
        :param placeholder_expression: The placeholder_expression of this PatchedPromptRequest.
        :param initial_value_expression: The initial_value_expression of this PatchedPromptRequest.
        """
        self.openapi_types = {
            'name': str,
            'field_key': str,
            'label': str,
            'type': PromptTypeEnum,
            'required': bool,
            'placeholder': str,
            'initial_value': str,
            'order': int,
            'promptstage_set': List[StageRequest],
            'sub_text': str,
            'placeholder_expression': bool,
            'initial_value_expression': bool
        }

        self.attribute_map = {
            'name': 'name',
            'field_key': 'field_key',
            'label': 'label',
            'type': 'type',
            'required': 'required',
            'placeholder': 'placeholder',
            'initial_value': 'initial_value',
            'order': 'order',
            'promptstage_set': 'promptstage_set',
            'sub_text': 'sub_text',
            'placeholder_expression': 'placeholder_expression',
            'initial_value_expression': 'initial_value_expression'
        }

        self._name = name
        self._field_key = field_key
        self._label = label
        self._type = type
        self._required = required
        self._placeholder = placeholder
        self._initial_value = initial_value
        self._order = order
        self._promptstage_set = promptstage_set
        self._sub_text = sub_text
        self._placeholder_expression = placeholder_expression
        self._initial_value_expression = initial_value_expression

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedPromptRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedPromptRequest of this PatchedPromptRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this PatchedPromptRequest.


        :return: The name of this PatchedPromptRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PatchedPromptRequest.


        :param name: The name of this PatchedPromptRequest.
        :type name: str
        """
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name

    @property
    def field_key(self):
        """Gets the field_key of this PatchedPromptRequest.

        Name of the form field, also used to store the value

        :return: The field_key of this PatchedPromptRequest.
        :rtype: str
        """
        return self._field_key

    @field_key.setter
    def field_key(self, field_key):
        """Sets the field_key of this PatchedPromptRequest.

        Name of the form field, also used to store the value

        :param field_key: The field_key of this PatchedPromptRequest.
        :type field_key: str
        """
        if field_key is not None and len(field_key) < 1:
            raise ValueError("Invalid value for `field_key`, length must be greater than or equal to `1`")

        self._field_key = field_key

    @property
    def label(self):
        """Gets the label of this PatchedPromptRequest.


        :return: The label of this PatchedPromptRequest.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this PatchedPromptRequest.


        :param label: The label of this PatchedPromptRequest.
        :type label: str
        """
        if label is not None and len(label) < 1:
            raise ValueError("Invalid value for `label`, length must be greater than or equal to `1`")

        self._label = label

    @property
    def type(self):
        """Gets the type of this PatchedPromptRequest.


        :return: The type of this PatchedPromptRequest.
        :rtype: PromptTypeEnum
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PatchedPromptRequest.


        :param type: The type of this PatchedPromptRequest.
        :type type: PromptTypeEnum
        """

        self._type = type

    @property
    def required(self):
        """Gets the required of this PatchedPromptRequest.


        :return: The required of this PatchedPromptRequest.
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this PatchedPromptRequest.


        :param required: The required of this PatchedPromptRequest.
        :type required: bool
        """

        self._required = required

    @property
    def placeholder(self):
        """Gets the placeholder of this PatchedPromptRequest.

        Optionally provide a short hint that describes the expected input value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple choices.

        :return: The placeholder of this PatchedPromptRequest.
        :rtype: str
        """
        return self._placeholder

    @placeholder.setter
    def placeholder(self, placeholder):
        """Sets the placeholder of this PatchedPromptRequest.

        Optionally provide a short hint that describes the expected input value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple choices.

        :param placeholder: The placeholder of this PatchedPromptRequest.
        :type placeholder: str
        """

        self._placeholder = placeholder

    @property
    def initial_value(self):
        """Gets the initial_value of this PatchedPromptRequest.

        Optionally pre-fill the input with an initial value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple default choices.

        :return: The initial_value of this PatchedPromptRequest.
        :rtype: str
        """
        return self._initial_value

    @initial_value.setter
    def initial_value(self, initial_value):
        """Sets the initial_value of this PatchedPromptRequest.

        Optionally pre-fill the input with an initial value. When creating a fixed choice field, enable interpreting as expression and return a list to return multiple default choices.

        :param initial_value: The initial_value of this PatchedPromptRequest.
        :type initial_value: str
        """

        self._initial_value = initial_value

    @property
    def order(self):
        """Gets the order of this PatchedPromptRequest.


        :return: The order of this PatchedPromptRequest.
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this PatchedPromptRequest.


        :param order: The order of this PatchedPromptRequest.
        :type order: int
        """
        if order is not None and order > 2147483647:
            raise ValueError("Invalid value for `order`, must be a value less than or equal to `2147483647`")
        if order is not None and order < -2147483648:
            raise ValueError("Invalid value for `order`, must be a value greater than or equal to `-2147483648`")

        self._order = order

    @property
    def promptstage_set(self):
        """Gets the promptstage_set of this PatchedPromptRequest.


        :return: The promptstage_set of this PatchedPromptRequest.
        :rtype: List[StageRequest]
        """
        return self._promptstage_set

    @promptstage_set.setter
    def promptstage_set(self, promptstage_set):
        """Sets the promptstage_set of this PatchedPromptRequest.


        :param promptstage_set: The promptstage_set of this PatchedPromptRequest.
        :type promptstage_set: List[StageRequest]
        """

        self._promptstage_set = promptstage_set

    @property
    def sub_text(self):
        """Gets the sub_text of this PatchedPromptRequest.


        :return: The sub_text of this PatchedPromptRequest.
        :rtype: str
        """
        return self._sub_text

    @sub_text.setter
    def sub_text(self, sub_text):
        """Sets the sub_text of this PatchedPromptRequest.


        :param sub_text: The sub_text of this PatchedPromptRequest.
        :type sub_text: str
        """

        self._sub_text = sub_text

    @property
    def placeholder_expression(self):
        """Gets the placeholder_expression of this PatchedPromptRequest.


        :return: The placeholder_expression of this PatchedPromptRequest.
        :rtype: bool
        """
        return self._placeholder_expression

    @placeholder_expression.setter
    def placeholder_expression(self, placeholder_expression):
        """Sets the placeholder_expression of this PatchedPromptRequest.


        :param placeholder_expression: The placeholder_expression of this PatchedPromptRequest.
        :type placeholder_expression: bool
        """

        self._placeholder_expression = placeholder_expression

    @property
    def initial_value_expression(self):
        """Gets the initial_value_expression of this PatchedPromptRequest.


        :return: The initial_value_expression of this PatchedPromptRequest.
        :rtype: bool
        """
        return self._initial_value_expression

    @initial_value_expression.setter
    def initial_value_expression(self, initial_value_expression):
        """Sets the initial_value_expression of this PatchedPromptRequest.


        :param initial_value_expression: The initial_value_expression of this PatchedPromptRequest.
        :type initial_value_expression: bool
        """

        self._initial_value_expression = initial_value_expression
