# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class PatchedWebAuthnDeviceRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None):
        """PatchedWebAuthnDeviceRequest - a model defined in OpenAPI

        :param name: The name of this PatchedWebAuthnDeviceRequest.
        """
        self.openapi_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedWebAuthnDeviceRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedWebAuthnDeviceRequest of this PatchedWebAuthnDeviceRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this PatchedWebAuthnDeviceRequest.


        :return: The name of this PatchedWebAuthnDeviceRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PatchedWebAuthnDeviceRequest.


        :param name: The name of this PatchedWebAuthnDeviceRequest.
        :type name: str
        """
        if name is not None and len(name) > 200:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `200`")
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")

        self._name = name
