# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.model_enum import ModelEnum
from authentik_openapi import util


class PatchedPermissionAssignRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, permissions: List[str]=None, model: ModelEnum=None, object_pk: str=None):
        """PatchedPermissionAssignRequest - a model defined in OpenAPI

        :param permissions: The permissions of this PatchedPermissionAssignRequest.
        :param model: The model of this PatchedPermissionAssignRequest.
        :param object_pk: The object_pk of this PatchedPermissionAssignRequest.
        """
        self.openapi_types = {
            'permissions': List[str],
            'model': ModelEnum,
            'object_pk': str
        }

        self.attribute_map = {
            'permissions': 'permissions',
            'model': 'model',
            'object_pk': 'object_pk'
        }

        self._permissions = permissions
        self._model = model
        self._object_pk = object_pk

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PatchedPermissionAssignRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PatchedPermissionAssignRequest of this PatchedPermissionAssignRequest.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def permissions(self):
        """Gets the permissions of this PatchedPermissionAssignRequest.


        :return: The permissions of this PatchedPermissionAssignRequest.
        :rtype: List[str]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this PatchedPermissionAssignRequest.


        :param permissions: The permissions of this PatchedPermissionAssignRequest.
        :type permissions: List[str]
        """

        self._permissions = permissions

    @property
    def model(self):
        """Gets the model of this PatchedPermissionAssignRequest.


        :return: The model of this PatchedPermissionAssignRequest.
        :rtype: ModelEnum
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this PatchedPermissionAssignRequest.


        :param model: The model of this PatchedPermissionAssignRequest.
        :type model: ModelEnum
        """

        self._model = model

    @property
    def object_pk(self):
        """Gets the object_pk of this PatchedPermissionAssignRequest.


        :return: The object_pk of this PatchedPermissionAssignRequest.
        :rtype: str
        """
        return self._object_pk

    @object_pk.setter
    def object_pk(self, object_pk):
        """Sets the object_pk of this PatchedPermissionAssignRequest.


        :param object_pk: The object_pk of this PatchedPermissionAssignRequest.
        :type object_pk: str
        """
        if object_pk is not None and len(object_pk) < 1:
            raise ValueError("Invalid value for `object_pk`, length must be greater than or equal to `1`")

        self._object_pk = object_pk
