# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi.models.contextual_flow_info import ContextualFlowInfo
from authentik_openapi.models.error_detail import ErrorDetail
from authentik_openapi.models.stage_prompt import StagePrompt
from authentik_openapi import util


class PromptChallenge(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, flow_info: ContextualFlowInfo=None, component: str='ak-stage-prompt', response_errors: Dict[str, List[ErrorDetail]]=None, fields: List[StagePrompt]=None):
        """PromptChallenge - a model defined in OpenAPI

        :param flow_info: The flow_info of this PromptChallenge.
        :param component: The component of this PromptChallenge.
        :param response_errors: The response_errors of this PromptChallenge.
        :param fields: The fields of this PromptChallenge.
        """
        self.openapi_types = {
            'flow_info': ContextualFlowInfo,
            'component': str,
            'response_errors': Dict[str, List[ErrorDetail]],
            'fields': List[StagePrompt]
        }

        self.attribute_map = {
            'flow_info': 'flow_info',
            'component': 'component',
            'response_errors': 'response_errors',
            'fields': 'fields'
        }

        self._flow_info = flow_info
        self._component = component
        self._response_errors = response_errors
        self._fields = fields

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PromptChallenge':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PromptChallenge of this PromptChallenge.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def flow_info(self):
        """Gets the flow_info of this PromptChallenge.


        :return: The flow_info of this PromptChallenge.
        :rtype: ContextualFlowInfo
        """
        return self._flow_info

    @flow_info.setter
    def flow_info(self, flow_info):
        """Sets the flow_info of this PromptChallenge.


        :param flow_info: The flow_info of this PromptChallenge.
        :type flow_info: ContextualFlowInfo
        """

        self._flow_info = flow_info

    @property
    def component(self):
        """Gets the component of this PromptChallenge.


        :return: The component of this PromptChallenge.
        :rtype: str
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this PromptChallenge.


        :param component: The component of this PromptChallenge.
        :type component: str
        """

        self._component = component

    @property
    def response_errors(self):
        """Gets the response_errors of this PromptChallenge.


        :return: The response_errors of this PromptChallenge.
        :rtype: Dict[str, List[ErrorDetail]]
        """
        return self._response_errors

    @response_errors.setter
    def response_errors(self, response_errors):
        """Sets the response_errors of this PromptChallenge.


        :param response_errors: The response_errors of this PromptChallenge.
        :type response_errors: Dict[str, List[ErrorDetail]]
        """

        self._response_errors = response_errors

    @property
    def fields(self):
        """Gets the fields of this PromptChallenge.


        :return: The fields of this PromptChallenge.
        :rtype: List[StagePrompt]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this PromptChallenge.


        :param fields: The fields of this PromptChallenge.
        :type fields: List[StagePrompt]
        """
        if fields is None:
            raise ValueError("Invalid value for `fields`, must not be `None`")

        self._fields = fields
