# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class ProviderTypeEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    APPLE = 'apple'
    OPENIDCONNECT = 'openidconnect'
    AZUREAD = 'azuread'
    DISCORD = 'discord'
    FACEBOOK = 'facebook'
    GITHUB = 'github'
    GITLAB = 'gitlab'
    GOOGLE = 'google'
    MAILCOW = 'mailcow'
    OKTA = 'okta'
    PATREON = 'patreon'
    REDDIT = 'reddit'
    TWITCH = 'twitch'
    TWITTER = 'twitter'

    def __init__(self):
        """ProviderTypeEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ProviderTypeEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ProviderTypeEnum of this ProviderTypeEnum.
        """
        return util.deserialize_model(dikt, cls)
