# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class SeverityEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NOTICE = 'notice'
    WARNING = 'warning'
    ALERT = 'alert'

    def __init__(self):
        """SeverityEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SeverityEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SeverityEnum of this SeverityEnum.
        """
        return util.deserialize_model(dikt, cls)
