# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class SyncObjectModelEnum(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    AUTHENTIK_PERIOD_CORE_PERIOD_MODELS_PERIOD_USER = 'authentik.core.models.User'
    AUTHENTIK_PERIOD_CORE_PERIOD_MODELS_PERIOD_GROUP = 'authentik.core.models.Group'

    def __init__(self):
        """SyncObjectModelEnum - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SyncObjectModelEnum':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SyncObjectModelEnum of this SyncObjectModelEnum.
        """
        return util.deserialize_model(dikt, cls)
