# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from authentik_openapi.models.base_model import Model
from authentik_openapi import util


class TOTPDevice(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, pk: int=None):
        """TOTPDevice - a model defined in OpenAPI

        :param name: The name of this TOTPDevice.
        :param pk: The pk of this TOTPDevice.
        """
        self.openapi_types = {
            'name': str,
            'pk': int
        }

        self.attribute_map = {
            'name': 'name',
            'pk': 'pk'
        }

        self._name = name
        self._pk = pk

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TOTPDevice':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TOTPDevice of this TOTPDevice.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this TOTPDevice.

        The human-readable name of this device.

        :return: The name of this TOTPDevice.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TOTPDevice.

        The human-readable name of this device.

        :param name: The name of this TOTPDevice.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 64:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `64`")

        self._name = name

    @property
    def pk(self):
        """Gets the pk of this TOTPDevice.


        :return: The pk of this TOTPDevice.
        :rtype: int
        """
        return self._pk

    @pk.setter
    def pk(self, pk):
        """Sets the pk of this TOTPDevice.


        :param pk: The pk of this TOTPDevice.
        :type pk: int
        """
        if pk is None:
            raise ValueError("Invalid value for `pk`, must not be `None`")

        self._pk = pk
