# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.10.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.compatibility_mode_enum import CompatibilityModeEnum

class TestCompatibilityModeEnum(unittest.TestCase):
    """CompatibilityModeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompatibilityModeEnum(self):
        """Test CompatibilityModeEnum"""
        # inst = CompatibilityModeEnum()

if __name__ == '__main__':
    unittest.main()
