# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.10.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.patched_user_ldap_source_connection_request import PatchedUserLDAPSourceConnectionRequest

class TestPatchedUserLDAPSourceConnectionRequest(unittest.TestCase):
    """PatchedUserLDAPSourceConnectionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedUserLDAPSourceConnectionRequest:
        """Test PatchedUserLDAPSourceConnectionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedUserLDAPSourceConnectionRequest`
        """
        model = PatchedUserLDAPSourceConnectionRequest()
        if include_optional:
            return PatchedUserLDAPSourceConnectionRequest(
                user = 56,
                source = '',
                identifier = '0'
            )
        else:
            return PatchedUserLDAPSourceConnectionRequest(
        )
        """

    def testPatchedUserLDAPSourceConnectionRequest(self):
        """Test PatchedUserLDAPSourceConnectionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
