# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.10.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.schedule_request import ScheduleRequest

class TestScheduleRequest(unittest.TestCase):
    """ScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScheduleRequest:
        """Test ScheduleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScheduleRequest`
        """
        model = ScheduleRequest()
        if include_optional:
            return ScheduleRequest(
                rel_obj_id = '0',
                crontab = '0',
                paused = True
            )
        else:
            return ScheduleRequest(
                crontab = '0',
        )
        """

    def testScheduleRequest(self):
        """Test ScheduleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
