# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2025.10.0-rc1
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.task_aggregated_status_enum import TaskAggregatedStatusEnum

class TestTaskAggregatedStatusEnum(unittest.TestCase):
    """TaskAggregatedStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskAggregatedStatusEnum(self):
        """Test TaskAggregatedStatusEnum"""
        # inst = TaskAggregatedStatusEnum()

if __name__ == '__main__':
    unittest.main()
