# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.8.3
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.api.oauth2_api import Oauth2Api


class TestOauth2Api(unittest.IsolatedAsyncioTestCase):
    """Oauth2Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = Oauth2Api()

    async def asyncTearDown(self) -> None:
        pass

    async def test_oauth2_access_tokens_destroy(self) -> None:
        """Test case for oauth2_access_tokens_destroy

        """
        pass

    async def test_oauth2_access_tokens_list(self) -> None:
        """Test case for oauth2_access_tokens_list

        """
        pass

    async def test_oauth2_access_tokens_retrieve(self) -> None:
        """Test case for oauth2_access_tokens_retrieve

        """
        pass

    async def test_oauth2_access_tokens_used_by_list(self) -> None:
        """Test case for oauth2_access_tokens_used_by_list

        """
        pass

    async def test_oauth2_authorization_codes_destroy(self) -> None:
        """Test case for oauth2_authorization_codes_destroy

        """
        pass

    async def test_oauth2_authorization_codes_list(self) -> None:
        """Test case for oauth2_authorization_codes_list

        """
        pass

    async def test_oauth2_authorization_codes_retrieve(self) -> None:
        """Test case for oauth2_authorization_codes_retrieve

        """
        pass

    async def test_oauth2_authorization_codes_used_by_list(self) -> None:
        """Test case for oauth2_authorization_codes_used_by_list

        """
        pass

    async def test_oauth2_refresh_tokens_destroy(self) -> None:
        """Test case for oauth2_refresh_tokens_destroy

        """
        pass

    async def test_oauth2_refresh_tokens_list(self) -> None:
        """Test case for oauth2_refresh_tokens_list

        """
        pass

    async def test_oauth2_refresh_tokens_retrieve(self) -> None:
        """Test case for oauth2_refresh_tokens_retrieve

        """
        pass

    async def test_oauth2_refresh_tokens_used_by_list(self) -> None:
        """Test case for oauth2_refresh_tokens_used_by_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
